# Generated by Django 3.2.3 on 2021-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(help_text='A unique order reference.', max_length=128, unique=True, verbose_name='Reference'),
        ),
    ]
