# Generated by Django 3.0.2 on 2020-02-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesmanorders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('salesmanorders.order',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('salesmanorders.orderitem',),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('salesmanorders.ordernote',),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('salesmanorders.orderpayment',),
        ),
    ]
