# Generated by Django 4.0.3 on 2022-03-14 09:19

import secrets
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import salesman.orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basket",
                "verbose_name_plural": "Baskets",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvalidProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        help_text="A unique order reference.",
                        max_length=128,
                        unique=True,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="NEW",
                        help_text=(
                            "Changing order status might trigger a notification to "
                            "customer."
                        ),
                        max_length=128,
                        verbose_name="Status",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text=(
                            "Allow non-authenticated customer to access the order with "
                            "token. To access order suply a '?token={token}' in url "
                            "querystring."
                        ),
                        max_length=128,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="Shipping address"),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Billing address"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Total",
                    ),
                ),
                (
                    "_extra",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="black",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        choices=[("64", "64G"), ("128", "128G"), ("256", "256G")],
                        default="64",
                        max_length=50,
                    ),
                ),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.phone"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Is accessible to the customer?",
                        verbose_name="Public",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "order",
                    salesman.orders.models.ParentalForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.SALESMAN_ORDER_MODEL,
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(max_length=128, verbose_name="Product type"),
                ),
                (
                    "product_id",
                    models.PositiveIntegerField(null=True, verbose_name="Product id"),
                ),
                (
                    "product_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Product data"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Unit price"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Subtotal"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Total"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "_extra",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra"),
                ),
                (
                    "order",
                    salesman.orders.models.ParentalForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.SALESMAN_ORDER_MODEL,
                        verbose_name="Order",
                    ),
                ),
                (
                    "product_content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Amount"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(max_length=128, verbose_name="Transaction ID"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Payment method"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "order",
                    salesman.orders.models.ParentalForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.SALESMAN_ORDER_MODEL,
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "abstract": False,
                "unique_together": {("order", "transaction_id")},
            },
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.SlugField(max_length=128, verbose_name="Reference")),
                ("product_id", models.PositiveIntegerField(verbose_name="Product id")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.SALESMAN_BASKET_MODEL,
                        verbose_name="Basket",
                    ),
                ),
                (
                    "product_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["date_created"],
                "abstract": False,
                "unique_together": {("basket", "ref")},
            },
        ),
    ]
