# Generated by Django 4.0.3 on 2022-03-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanbasket', '0002_alter_json_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='owner',
            new_name='user',
        ),
    ]
